Remove unecessary if statement
myparcelnl/magento pull request #507
Opened 2020-11-03 13:47 UTC by robindelaater

2020-11-03 14:11 UTC, reindert-vetter commented
https://github.com/myparcelnl/sdk/pull/275#pullrequestreview-522530926 moet eerst getest en gemerged worden voordat ik deze goedkeur.

2020-11-03 14:20 UTC, RichardPerdaan requested changes

2020-11-03 14:20 UTC, RichardPerdaan commented on Controller/Adminhtml/Order/CreateAndPrintMyParcelTrack.php
> -            if ($destinationCountry != AbstractConsignment::CC_NL && $destinationCountry != AbstractConsignment::CC_BE) {
Moest de $destinationCountry != AbstractConsignment::CC_NL niet blijven staan?

2020-11-03 14:27 UTC, RichardPerdaan approved these changes

2020-11-17 13:03 UTC, reindert-vetter approved these changes

2020-11-17 14:03 UTC, merged