Fix delivery methods and prices
myparcelnl/magento pull request #518
Opened 2020-11-27 09:22 UTC by RichardPerdaan

2020-11-27 10:01 UTC, robindelaater submitted a review, later dismissed

2020-12-01 12:11 UTC, EdieLemoine requested changes

2020-12-01 12:11 UTC, EdieLemoine commented on Model/Rate/Result.php
>          foreach ($this->getMethods() as $alias => $settingPath) {
Je gebruikt `$alias` niet

2020-12-01 12:11 UTC, EdieLemoine commented on Model/Rate/Result.php
> +        $map             = Data::CARRIERS_XML_PATH_MAP['postnl'];
Moet dit echt een hard coded `postnl`etje zijn?

2020-12-01 12:11 UTC, EdieLemoine commented on Model/Rate/Result.php
> +     * @param $settingPath
type ;)

2020-12-01 12:38 UTC, EdieLemoine approved these changes

2020-12-01 12:38 UTC, reindert-vetter approved these changes

2020-12-22 14:09 UTC, merged