fix: correct tracktrace link in ordergrid
myparcelnl/magento pull request #607
Opened 2021-11-22 16:15 UTC by joerivanveen

2021-11-24 13:04 UTC, EdieLemoine requested changes

2021-11-24 13:04 UTC, EdieLemoine commented on Model/Sales/MagentoCollection.php
> +        $this->myParcelCollection = (new MyParcelCollection())->setUserAgent('Magento2 ' .
Waarom de spatie? Waarom niet `setUserAgents`? De origin in de api is `Magento`, niet `Magento2`. Dit werkt overigens niet als er ooit iets qua `filter` of `map` gedaan wordt op de collection.

2021-11-24 13:04 UTC, EdieLemoine commented on Ui/Component/Listing/Column/TrackAndTrace.php
> +            $html .= '<a class="myparcel-barcode-link" target="_blank" href="';
Liever sprintf voor zoiets

2021-11-24 13:04 UTC, EdieLemoine commented on view/adminhtml/templates/order_view.phtml
> +            <?php echo TrackAndTrace::getTrackAndTraceLinksAsHtml($order) ;?>
spatie tussen functie en ;

2021-11-24 13:04 UTC, EdieLemoine commented on Ui/Component/Listing/Column/TrackAndTrace.php
>       * @param array $orderData
param klopt niet

2021-11-25 08:18 UTC, EdieLemoine requested changes

2021-11-25 08:18 UTC, EdieLemoine commented on Model/Sales/MagentoCollection.php
> +        $this->myParcelCollection = (new MyParcelCollection())->setUserAgents(['Magento2'=> $this->helper->getVersion()]);   }
formatting?

2021-11-25 08:18 UTC, EdieLemoine commented on view/adminhtml/templates/order_view.phtml
> +            <?php echo TrackAndTrace::getTrackAndTraceLinksAsHtml($order);?>
Deze ook ff formatten 🙏🏼

2021-11-25 08:30 UTC, RichardPerdaan submitted a review, later dismissed

2021-11-25 09:08 UTC, EdieLemoine approved these changes

2021-11-25 09:29 UTC, RichardPerdaan approved these changes

2021-11-26 08:11 UTC, merged