feat: add pickup disable option for mailbox packages
myparcelnl/magento pull request #611
Opened 2021-12-08 08:34 UTC by markernst97

2021-12-08 08:45 UTC, RichardPerdaan requested changes

2021-12-08 08:45 UTC, RichardPerdaan commented on Model/Quote/Checkout.php
> +            $mailboxPackage   = $this->getPackageType()['packageType'] === 'mailbox';
'mailbox' zou je kunnen vervangen door een constants

2021-12-08 08:45 UTC, RichardPerdaan commented on Model/Quote/Checkout.php
> +                'allowPickupLocations'  => $this->package->deliveryOptionsDisabled || ($mailboxPackage && !$showPickup) ? false : $this->helper->getBoolConfig($carrierPath[$carrier], 'pickup/active')
Misschien is het mooier om de checks die je hier doet in een nieuwe/bestaande method te plaatsen. Dan hoef je hier alleen maar de method aan te roepen.

2021-12-10 09:36 UTC, EdieLemoine submitted a review, later dismissed
mooie pr naam 👼🏼

2021-12-10 09:36 UTC, EdieLemoine commented on Model/Quote/Checkout.php
> +            $isMailboxPackage = $this->getPackageType()['packageType'] === self::PACKAGE_TYPE_MAILBOX;
graag yoda notation gebruiken

2021-12-10 09:36 UTC, EdieLemoine commented on Model/Quote/Checkout.php
> +        return ! ($this->package->deliveryOptionsDisabled || ($isMailboxPackage && ! $showPickup))
Dit is een veel te grote en slecht leesbare condition. Je hebt ook 2 parameters die niet nodig zijn omdat ze alleen hiervoor gebruikt worden. Je kunt dit refactoren naar zoiets, dan houd je alleen de parameter `$carrier` over en kun je wel in een oogopslag door de namen van de variabelen te lezen de logica snappen.

```
$isMailboxPackage     = $this->getPackageType()['packageType'] === self::PACKAGE_TYPE_MAILBOX;
$pickupEnabled        = $this->helper->getBoolConfig($carrier, 'pickup/active');
$showPickupForMailbox = $this->helper->getBoolConfig($carrierPath[$carrier], 'mailbox/pickup_mailbox');
$showPickup           = ! $isMailboxPackage || $showPickupForMailbox;

return ! $this->package->deliveryOptionsDisabled && $pickupEnabled && $showPickup;
```

2021-12-13 09:55 UTC, joerivanveen approved these changes

2021-12-14 08:18 UTC, RichardPerdaan approved these changes

2021-12-17 11:48 UTC, merged