fix: error delivery date is too early
myparcelnl/magento pull request #616
Opened 2021-12-15 13:01 UTC by RichardPerdaan

- Resolves #613 
- Resolves #615

2021-12-16 08:39 UTC, markernst97 submitted a review, later dismissed

2021-12-17 10:59 UTC, joerivanveen requested changes

2021-12-17 10:59 UTC, joerivanveen commented on Helper/Data.php
> +        $checkoutData = json_decode($date, true)['date'];
$checkoutDate met een 'e' aan het eind toch?

2021-12-17 11:41 UTC, RichardPerdaan commented on Helper/Data.php
> +        $checkoutData = json_decode($date, true)['date'];
done

2021-12-17 11:47 UTC, joerivanveen submitted a review, later dismissed

2021-12-17 13:10 UTC, markernst97 submitted a review, later dismissed

2021-12-31 12:28 UTC, joerivanveen approved these changes

2022-01-03 09:56 UTC, markernst97 approved these changes

2022-01-05 07:57 UTC, merged