feat: add insurance setting for shipments to BE
myparcelnl/magento pull request #617
Opened 2021-12-16 14:09 UTC by joerivanveen

2021-12-17 13:10 UTC, markernst97 submitted a review, later dismissed

2021-12-23 12:24 UTC, joerivanveen commented on Model/Source/DefaultOptions.php
> +            return $this->getDefault('insurance_belgium') ? 500 : 0;
geen magic numbers

2021-12-23 12:24 UTC, EdieLemoine requested changes

2021-12-23 12:24 UTC, EdieLemoine commented on view/adminhtml/templates/support_tab.phtml
> +                                                    <?= __('As of january 1st 2022 shipments to Belgium will be insured based on default export settings.');?>
```suggestion
                                                    <?= __('As of January 1st 2022 shipments to Belgium will be insured based on default export settings.');?>
```

2021-12-23 12:26 UTC, joerivanveen commented on i18n/nl_NL.csv
> +As of january 1st 2022 shipments to Belgium will be insured based on default export settings.,Zendingen naar Belgie worden per 1 januari 2022 verzekerd op basis van de default export instellingen.
```suggestion
As of January 1st 2022 shipments to Belgium will be insured based on default export settings.,Zendingen naar Belgie worden per 1 januari 2022 verzekerd op basis van de default export instellingen.
```

2021-12-27 09:09 UTC, markernst97 submitted a review, later dismissed

2021-12-27 16:09 UTC, RichardPerdaan submitted a review, later dismissed

2021-12-28 12:15 UTC, markernst97 approved these changes

2021-12-28 12:29 UTC, RichardPerdaan approved these changes

2021-12-28 12:35 UTC, merged