fix: can add multiple consignments for all package types
myparcelnl/magento pull request #626
Opened 2022-01-11 16:31 UTC by joerivanveen

2022-01-13 15:46 UTC, RichardPerdaan requested changes

2022-01-13 15:46 UTC, RichardPerdaan commented on Model/Sales/MagentoCollection.php
> +        return $consignment::CC_NL === $country
Het is ook mogelijk om multicollo naar BE te versturen

2022-01-13 16:05 UTC, RichardPerdaan submitted a review, later dismissed

2022-01-13 16:24 UTC, EdieLemoine submitted a review, later dismissed

2022-01-18 08:44 UTC, RichardPerdaan approved these changes

2022-01-18 09:05 UTC, EdieLemoine requested changes

2022-01-18 09:05 UTC, EdieLemoine commented on Model/Sales/TrackTraceHolder.php
> +            ->setReturn($deliveryType !== AbstractConsignment::DELIVERY_TYPE_PICKUP
yoda!

2022-01-18 09:05 UTC, EdieLemoine commented on Model/Sales/MagentoCollection.php
> +                if (isset($myParcelTrack->status)) {
Kan je isset niet weglaten?

2022-01-18 09:13 UTC, EdieLemoine approved these changes

2022-01-18 09:29 UTC, RichardPerdaan approved these changes

2022-01-18 12:21 UTC, merged