feat(pps): add shipment options to pps orders
myparcelnl/magento pull request #627
Opened 2022-01-12 12:44 UTC by markernst97

2022-01-13 09:19 UTC, EdieLemoine requested changes

2022-01-13 09:19 UTC, EdieLemoine commented on Helper/ShipmentOptions.php
> +     *
phpdoc mist

2022-01-13 09:19 UTC, EdieLemoine commented on Helper/ShipmentOptions.php
> +        getValueFromAttribute(
beetje lelijke indenting hier

2022-01-13 09:19 UTC, EdieLemoine commented on Helper/ShipmentOptions.php
> +    private function getValueOfOption($optionKey): bool
En die default is ook altijd een boolean? Moet je hem dan niet `optionIsEnabled` oid noemen?

2022-01-13 09:19 UTC, EdieLemoine commented on Model/Sales/MagentoOrderCollection.php
> +    private Recipient $billingRecipient;
Wow! Uhm, supporten wij niets meer onder php 7.4?

2022-01-13 09:19 UTC, EdieLemoine commented on Model/Sales/MagentoOrderCollection.php
> +                $pickupLocation     = new PickupLocation([
uitlijnen

2022-01-13 09:19 UTC, EdieLemoine commented on Model/Sales/MagentoOrderCollection.php
>      public function downloadPdfOfLabels()
als je hier toch bent kun je ook wel ff een return type toevoegen 👼🏼

2022-01-13 09:19 UTC, EdieLemoine commented on Model/Sales/TrackTraceHolder.php
> +     * @var ShipmentOptions
Alle phpdoc classes moeten FQCNs zijn, dus `\De\Volledige\Namespace`

2022-01-13 09:19 UTC, EdieLemoine commented on Model/Sales/TrackTraceHolder.php
> +        $deliveryOptions = json_decode($checkoutData, true, 512, JSON_THROW_ON_ERROR);
Supporten we niets meer onder php 7.3?

2022-01-13 09:19 UTC, EdieLemoine commented on Model/Sales/TrackTraceHolder.php
> +        if ($options['package_type'] && $options['package_type'] !== 'default') {
yoda notation

2022-01-13 09:19 UTC, EdieLemoine commented on Model/Sales/TrackTraceHolder.php
> +        if ($apiKey === null) {
yoda

2022-01-13 09:19 UTC, EdieLemoine commented on Model/Sales/TrackTraceHolder.php
> +            ::getValueFromAttribute(
rare indenting

2022-01-13 09:31 UTC, joerivanveen requested changes

2022-01-13 09:31 UTC, joerivanveen commented on Model/Sales/MagentoOrderCollection.php
> +            $deliveryOptions         = json_decode($myparcelDeliveryOptions, true, 512, JSON_THROW_ON_ERROR);
Dit is mogelijk gevaarlijk bij orders die geen delivery options hebben (dat kan als je een order kopieert of wanneer om wat voor reden dan ook, bv omdat eerst een andere verzendmethode was gekozen, de frontend geen delivery options heeft opgeslagen), ik zou eerder hier een foutafhandeling op zetten. Wordt dit specifiek getest?

2022-01-13 09:31 UTC, joerivanveen commented on Model/Sales/MagentoOrderCollection.php
> +        $inlineDownload = $this->options['request_type'] === 'open_new_tab';
Yoda is preferred

2022-01-13 09:31 UTC, joerivanveen commented on Model/Source/DefaultOptions.php
> +    public function getPackageType(bool $returnName = false)
Ik zou dit alsjeblieft in een aparte method doen: getPackageTypeName, die evt. deze weer aanroept, zodat het direct duidelijk is bij gebruik: getPackageTypeName returnt een string, getPackageType returnt altijd een int, en dat is dus de id dan, er is al veel verwarring mbt packageType door de hele plugin vind ik.

2022-01-14 10:04 UTC, joerivanveen requested changes

2022-01-14 10:04 UTC, joerivanveen commented on Model/Sales/MagentoOrderCollection.php
>              if ($deliveryOptions['isPickup']) {
Weet je zeker dat alle orders altijd deliveryoptions hebben, anders geeft dit een warning (key niet gevonden ofzo)

2022-01-18 08:44 UTC, RichardPerdaan approved these changes

2022-01-18 13:07 UTC, joerivanveen submitted a review, later dismissed

2022-01-18 13:47 UTC, EdieLemoine submitted a review, later dismissed

2022-01-19 09:31 UTC, RichardPerdaan submitted a review, later dismissed

2022-01-19 09:42 UTC, EdieLemoine submitted a review, later dismissed

2022-01-19 09:42 UTC, EdieLemoine commented on Helper/ShipmentOptions.php
> +    {
deze ,a m

2022-01-20 14:40 UTC, EdieLemoine approved these changes

2022-01-20 15:14 UTC, joerivanveen submitted a review, later dismissed

2022-01-21 08:57 UTC, merged