fix(pps): separate street and number when exporting order
myparcelnl/magento pull request #628
Opened 2022-01-12 14:19 UTC by markernst97

2022-01-13 09:20 UTC, EdieLemoine requested changes

2022-01-13 09:20 UTC, EdieLemoine commented on Model/Sales/MagentoOrderCollection.php
> +        $formattedDeliveryOptions = json_decode($this->order['myparcel_delivery_options'], true, 512, JSON_THROW_ON_ERROR);
supporten we php < 7.3?

2022-01-13 09:33 UTC, joerivanveen requested changes

2022-01-13 09:33 UTC, joerivanveen commented on Model/Sales/MagentoOrderCollection.php
> +        $formattedDeliveryOptions = json_decode($this->order['myparcel_delivery_options'], true, 512, JSON_THROW_ON_ERROR);
Scherp

2022-01-13 09:42 UTC, EdieLemoine commented on Model/Sales/MagentoOrderCollection.php
> +        $formattedDeliveryOptions = json_decode($this->order['myparcel_delivery_options'], true, 512, JSON_THROW_ON_ERROR);
🔪

2022-01-13 16:03 UTC, RichardPerdaan approved these changes

2022-01-13 16:12 UTC, joerivanveen approved these changes

2022-01-13 16:15 UTC, joerivanveen commented on Model/Sales/MagentoOrderCollection.php
> +        $carrier                  = ConsignmentFactory::createByCarrierName($formattedDeliveryOptions['carrier']);
Dit kan een warning geven als json_decode null teruggegeven heeft (een reele situatie)

2022-01-19 08:56 UTC, RichardPerdaan approved these changes

2022-01-19 09:39 UTC, EdieLemoine approved these changes

2022-01-19 10:53 UTC, merged