fix(pps): errors when exporting bbp/row/dpz/eu orders
myparcelnl/magento pull request #635
Opened 2022-01-25 10:29 UTC by markernst97

2022-01-25 12:13 UTC, EdieLemoine approved these changes

2022-01-25 12:13 UTC, EdieLemoine commented on Model/Sales/MagentoOrderCollection.php
>                  $deliveryOptions['packageType'] = AbstractConsignment::PACKAGE_TYPE_PACKAGE_NAME ;
```suggestion
                $deliveryOptions['packageType'] = AbstractConsignment::PACKAGE_TYPE_PACKAGE_NAME;
```

2022-01-27 10:51 UTC, joerivanveen requested changes

2022-01-27 10:51 UTC, joerivanveen commented on Model/Source/DefaultOptions.php
> +        if (! empty(self::$chosenOptions)) {
Willen we echt `if (! empty($shizzle))` gebruiken als dat hetzelfde is als `if ($shizzle)`?

2022-01-27 10:51 UTC, joerivanveen commented on Helper/ShipmentOptions.php
> +        if (! isset($options[$key]) || ! array_key_exists($key, $options)) {
Als je toch `return null` doet kan je de `array_key_exists` hier achterwege laten volgens mij, wat er werkelijk gebeurt is nu nodeloos complex genoteerd volgens mij. Volgens mij gebeurt er dit: `return isset($options[$key]) ? (bool) $options[$key] : null);` maar dat is mogelijk niet wat je wilt. Ik denk dat je dit bedoelt: `if ($options[$key] || array_key_exists[$key, $options]) { return (bool)$options[$key]; } return null;` maar dan netjes opgeschreven

2022-01-27 10:51 UTC, joerivanveen commented on Helper/ShipmentOptions.php
> +        if (! isset($options[$key]) || ! array_key_exists($key, $options)) {
Wanneer isset false teruggeeft, is de eerste conditie true, dus geeft ie null terug. Als isset true teruggeeft is de eerste conditie false, dus dan gaat ie naar array_key_exists kijken, maar die is altijd true, want isset is ook al true.

2022-01-27 10:51 UTC, joerivanveen commented on Model/Sales/MagentoOrderCollection.php
> +            if (! empty($deliveryOptions['isPickup'])) {
`! empty` is hetzelfde als ``;

2022-01-27 10:51 UTC, joerivanveen commented on Services/Normalizer/ConsignmentNormalizer.php
> +        $data['packageType']  = $data['package_type'] ?? AbstractConsignment::PACKAGE_TYPE_PACKAGE_NAME;
Hier gaat denk ik iets mis als de check op `package_type` is en de waarde in `packageType` komt...

2022-01-31 10:22 UTC, joerivanveen approved these changes

2022-02-01 08:41 UTC, RichardPerdaan submitted a review, later dismissed

2022-02-01 09:17 UTC, joerivanveen approved these changes

2022-02-01 09:20 UTC, RichardPerdaan approved these changes

2022-02-02 07:58 UTC, merged