fix(pps): export shipment options from order modal
myparcelnl/magento pull request #647
Opened 2022-02-08 13:46 UTC by markernst97

2022-02-08 13:47 UTC, EdieLemoine submitted a review, later dismissed

2022-02-08 16:24 UTC, RichardPerdaan approved these changes

2022-02-09 07:15 UTC, RichardPerdaan approved these changes

2022-02-09 09:15 UTC, EdieLemoine requested changes

2022-02-09 09:15 UTC, EdieLemoine commented on Helper/ShipmentOptions.php
> +        if ($options[$key] || false === $options[$key]) {
Dit gaat op allerlei manieren fout als `$key` niet in `$options` zit, wat blijkbaar mag gebeuren omdat deze functie public is. Plus, wat is hier de bedoeling van? 

Åls hij truthy of niet false is returnt hij null? Dus alleen lege string en lege array returnen null? En `$options[$key]` hoeft helemaal niet per se een boolean te zijn maar de functie verwacht wel altijd een boolean of null.

Kijk hier nog even goed naar, dit gaat websites omver trekken 😛

2022-02-09 09:15 UTC, EdieLemoine commented on Helper/ShipmentOptions.php
> +        $onlyRecipientFromSettings = $this->optionIsEnabled(self::ONLY_RECIPIENT);
De naam van deze variabele matcht niet echt met de naam van de functie die aangeroepen wordt, wat gebeurt hier nou echt?

En je mag van mij ook best dit schrijven:

```php
return $onlyRecipientFromOptions ?? $this->optionIsEnabled(self::ONLY_RECIPIENT);
```

Niet al te lang of onleesbaar en zorgt er wel voor dat als `$onlyRecipientFromOptions` niet null is dat `$optionIsEnabled` helemaal niet aangeroepen wordt

2022-02-09 11:15 UTC, EdieLemoine submitted a review, later dismissed

2022-02-09 12:03 UTC, RichardPerdaan submitted a review, later dismissed

2022-02-09 13:44 UTC, merged