fix: compatibility with php 8.1
myparcelnl/magento pull request #690
Opened 2022-06-16 08:45 UTC by Mark-Ernst

2022-06-16 12:44 UTC, joerivanveen requested changes

2022-06-16 12:44 UTC, joerivanveen commented on Model/Quote/SaveOrderBeforeSalesModelQuoteObserver.php
> +            $deliveryOptions     = $jsonDeliveryOptions ? json_decode($jsonDeliveryOptions, true, 512, JSON_THROW_ON_ERROR) : [];
JSON_THROW_ON_ERROR is pas vanaf php 7.3 en wij ondersteunen dacht ik 7.2 nog?

2022-06-16 12:44 UTC, joerivanveen commented on Model/Quote/SaveOrderBeforeSalesModelQuoteObserver.php
> +            $deliveryOptions     = $jsonDeliveryOptions ? json_decode($jsonDeliveryOptions, true, 512, JSON_THROW_ON_ERROR) : [];
Kan je niet bij $quote->getData zorgen dat $jsonDeliveryOptions niet null kan zijn? Dat maakt deze regel minder lang / lelijk / moeilijk.

2022-06-16 12:44 UTC, joerivanveen commented on Model/Sales/TrackTraceHolder.php
> +        $deliveryOptions                = $checkoutData ? json_decode($checkoutData, true) : [];
Hier zou ik ook bij het toewijzen van $checkoutData zorgen dat die niet null kan zijn

2022-06-16 12:44 UTC, joerivanveen commented on Model/Source/DefaultOptions.php
> +        self::$chosenOptions = $options ? json_decode($options, true) : [];
Zie eerdere opmerkingen

2022-06-20 14:33 UTC, joerivanveen approved these changes

2022-06-20 15:18 UTC, EdieLemoine approved these changes

2022-06-23 08:04 UTC, merged