fix: export order from order details
myparcelnl/magento pull request #693
Opened 2022-06-16 09:11 UTC by wthijmen

2022-06-16 12:31 UTC, joerivanveen requested changes

2022-06-16 12:31 UTC, joerivanveen commented on Block/Sales/NewShipment.php
> +        $this->orderCollection = $orderCollection ?? new MagentoOrderCollection($this->objectManager, $this->request);
Inderdaad (Codacity), waar komt $orderCollection vandaan?

2022-06-16 12:31 UTC, joerivanveen commented on Block/Sales/NewShipment.php
> +        return TrackTraceHolder::EXPORT_MODE_PPS == $this->orderCollection->getExportMode();
Altijd sterke vergelijkingen gebruiken (===)

2022-06-16 12:31 UTC, joerivanveen commented on Observer/NewShipment.php
> +        if (TrackTraceHolder::EXPORT_MODE_PPS === $this->orderCollection->getExportMode()) {
Hier heb je nu toch een method voor, of zie ik dat verkeerd?

2022-06-16 12:31 UTC, joerivanveen commented on Observer/NewShipment.php
> +        $collection->addAttributeToFilter('entity_id', ['in' => $orderId]);
Wanneer je toch naar deze pr kijkt, dubbelcheck / triplecheck dan even of deze $orderId inderdaad de entity_id is, en niet de increment_id

2022-06-20 11:58 UTC, Mark-Ernst approved these changes

2022-06-20 14:27 UTC, joerivanveen submitted a review, later dismissed

2022-06-23 13:38 UTC, Mark-Ernst approved these changes

2022-06-27 12:28 UTC, joerivanveen requested changes

2022-06-27 12:28 UTC, joerivanveen commented on Observer/NewShipment.php
> +            return;
Witregel boven return

2022-06-27 12:28 UTC, joerivanveen commented on Observer/NewShipment.php
>          $aHtml = $this->orderCollection->getHtmlForGridColumnsByTracks($shipment->getTracksCollection());
Graag witregel onder var toewijzing en if statement voor ademruimte

2022-06-27 12:42 UTC, joerivanveen approved these changes

2022-06-27 12:44 UTC, Mark-Ernst approved these changes

2022-06-27 13:59 UTC, merged