feat: allow custom amount of items in mailbox package
myparcelnl/magento pull request #695
Opened 2022-06-20 11:09 UTC by wthijmen

2022-06-20 15:01 UTC, joerivanveen requested changes
1) misschien is het netter om de querybuilder en bijbehorende methods nog iets meer te isoleren binnen de Setup qua mappen en namespace, maar misschien is dit voldoende hoor
2) heb je het getest met verschillende aantallen maximum mailbox items? Wanneer ik de code lees begrijp ik namelijk niet hoe het zou werken, dat hij automatisch switcht naar pakket indien nodig, bv met een artikel waar er 2 van in een mailbox passen en een artikel waarvan er 500 passen, en dat men er 1 van de eerste en 500 van de tweede bestelt, dan accepteert hij dat gewoon. Just checking.

2022-06-21 12:55 UTC, Mark-Ernst commented on Model/Sales/Package.php
> +     * @param int $items
```suggestion
     * @param int $percentage
```

2022-06-21 13:21 UTC, Mark-Ernst approved these changes

2022-06-21 14:32 UTC, joerivanveen approved these changes

2022-06-21 14:32 UTC, joerivanveen commented on Setup/ReplaceFitInMailbox.php
> +        return $resource->getConnection();
Witregel voor return

2022-06-23 08:17 UTC, Mark-Ernst approved these changes

2022-06-23 10:17 UTC, joerivanveen requested changes

2022-06-23 10:17 UTC, joerivanveen commented on Setup/Migrations/ReplaceFitInMailbox.php
> +        foreach($results as $entity) {
Codacy heeft wel een punt, bedoel je verderop in de loop misschien $entity->newEavAttributeId en $entity->oldeEavAttributeId? Ik vind hem zo nl. ook wel moeilijk te lezen (ik snap m niet...)

2022-06-23 10:17 UTC, joerivanveen commented on Setup/Migrations/ReplaceDisableCheckout.php
> +        foreach($results as $entity) {
Zelfde als die andere.

2022-06-23 13:44 UTC, joerivanveen submitted a review, later dismissed

2022-06-27 15:12 UTC, Mark-Ernst submitted a review, later dismissed

2022-06-27 15:33 UTC, EdieLemoine requested changes

2022-06-27 15:33 UTC, EdieLemoine commented on Model/Sales/Repository/PackageRepository.php
>          if (
yoda conditions hieronder

2022-06-27 15:33 UTC, EdieLemoine commented on Setup/Methods/Insert.php
> +        return 'INSERT INTO ' . $this->table
vermijd concatenation

2022-06-27 15:33 UTC, EdieLemoine commented on Setup/Methods/Insert.php
> +        foreach ($columns as $column) {
enters om blokken heen

2022-06-28 09:26 UTC, joerivanveen commented on Model/Sales/Repository/PackageRepository.php
> +            $productPercentage = $product->getQty() / 100 * $maxAmountProductInMailbox;
```suggestion
            $productPercentage = $product->getQty() * 100 / $maxAmountProductInMailbox;
```

2022-06-28 09:27 UTC, joerivanveen commented on Model/Sales/Repository/PackageRepository.php
> +            (100 <= $mailboxPercentage) &&
Haakjes zijn overbodig

2022-06-28 09:29 UTC, joerivanveen commented on Setup/Methods/Delete.php
> +            $this->conditions===[]
Yoda style en missende spaties (request change), maar voor de leesbaarheid is het misschien ook mogelijk om dit buiten de return statement voor te bereiden en niet in een ternary te stoppen (ter overweging)? Edit: ik zie dat dit zo verderop ook weer is, wat mij betreft (zie ook mijn vorige goedkeuring) laat je dit allemaal zoals je het gevonden hebt. Maar als we het echt netjes doen, moeten overal spaties en yoda style gehanteerd worden (krijg je er geen waarschuwingen voor in phpStorm?)

2022-06-28 09:34 UTC, joerivanveen commented on Setup/Migrations/ReplaceFitInMailbox.php
> +        return (null !== $entity['value']) ? round((100 / $entity['value'])) : $entity['value'] = 0;
Volgens de styleguide mogen we geen toewijzingen doen in statements die returnen of conditioneel zijn. Ik betwijfel ook of dat is wat je bedoelde hier...

2022-06-28 11:33 UTC, joerivanveen submitted a review, later dismissed

2022-06-29 09:10 UTC, Mark-Ernst submitted a review, later dismissed

2022-06-30 07:35 UTC, joerivanveen submitted a review, later dismissed

2022-06-30 08:39 UTC, EdieLemoine requested changes

2022-06-30 08:39 UTC, EdieLemoine commented on Setup/Methods/Delete.php
> +            ! $this->conditions
geen negated conditions, dus als je `!` zou willen gebruiken in een ja/nee conditie moet je degene zonder `!` vooraan zetten. (phpstorm kan dit makkelijk voor je omwisselen.)

Echter doen we ook geen `!` op arrays, liever `empty($array)`.

2022-06-30 08:39 UTC, EdieLemoine commented on Setup/Methods/Select.php
> +                    : implode(
rare indenting

2022-06-30 08:39 UTC, EdieLemoine commented on Setup/Methods/Select.php
> +                ! $this->join
hier ook `!`/`empty`

2022-06-30 08:39 UTC, EdieLemoine commented on Setup/Methods/Select.php
>                  true === $this->distinct ? 'DISTINCT ' : '',
niet op true checken, je types moeten goed genoeg zijn om dit niet nodig te maken, dus gewoon zo
```suggestion
                $this->distinct ? 'DISTINCT ' : '',
```

2022-06-30 08:55 UTC, EdieLemoine submitted a review, later dismissed

2022-06-30 08:57 UTC, Mark-Ernst submitted a review, later dismissed

2022-07-01 07:43 UTC, joerivanveen submitted a review, later dismissed

2022-07-01 10:17 UTC, Mark-Ernst approved these changes

2022-07-01 10:44 UTC, joerivanveen approved these changes

2022-07-01 10:45 UTC, merged