fix: only get available options for carriers
myparcelnl/magento pull request #703
Opened 2022-07-04 18:49 UTC by joerivanveen

Resolves #701

2022-07-05 07:08 UTC, wthijmen submitted a review, later dismissed

2022-07-05 15:18 UTC, Mark-Ernst requested changes

2022-07-05 15:18 UTC, Mark-Ernst commented on Model/Quote/Checkout.php
> +            $consignment         = ConsignmentFactory::createByCarrierName($carrier);
Deze uitlijning

2022-07-05 15:44 UTC, joerivanveen commented on Model/Quote/Checkout.php
> +            $consignment         = ConsignmentFactory::createByCarrierName($carrier);
```suggestion
            $consignment = ConsignmentFactory::createByCarrierName($carrier);
```

2022-07-05 19:05 UTC, Mark-Ernst approved these changes

2022-07-06 11:40 UTC, wthijmen approved these changes

2022-07-07 08:19 UTC, merged