display correct version to enduser
myparcelnl/magento pull request #706
Opened 2022-08-08 08:37 UTC by joerivanveen

Resolves #704

2022-08-08 08:46 UTC, wthijmen submitted a review, later dismissed

2022-08-08 14:29 UTC, Mark-Ernst submitted a review, later dismissed

2022-08-09 07:16 UTC, EdieLemoine requested changes
lockfile mist

2022-08-09 07:32 UTC, EdieLemoine approved these changes

2022-08-09 07:37 UTC, wthijmen approved these changes

2022-08-09 08:01 UTC, merged