fix: remove attributes on uninstall
myparcelnl/magento pull request #722
Opened 2022-10-18 12:30 UTC by Mark-Ernst

Resolves #720

2022-10-19 14:14 UTC, EdieLemoine requested changes

2022-10-19 14:14 UTC, EdieLemoine commented on Setup/Uninstall.php
> +     */
```suggestion
		 * @SuppressWarnings(PHPMD.UnusedLocalVariable)
     */
```

2022-10-25 13:24 UTC, wthijmen approved these changes

2022-10-25 14:25 UTC, joerivanveen approved these changes

2022-10-27 11:02 UTC, EdieLemoine approved these changes

2022-10-27 11:04 UTC, merged