feat(fulfilment): add order notes
myparcelnl/magento pull request #768
Opened 2023-07-13 09:56 UTC by joerivanveen

Needs myparcelnl/sdk#7.8.0

2023-07-17 12:41 UTC, EdieLemoine requested changes

2023-07-17 12:41 UTC, EdieLemoine commented on Model/Sales/MagentoOrderCollection.php
> +            if ($status->getComment()) {
unhappy flow eerst

2023-07-17 12:41 UTC, EdieLemoine commented on Model/Sales/MagentoOrderCollection.php
> +            });
liever geen reduce

2023-07-17 12:41 UTC, EdieLemoine commented on Observer/SalesOrderStatusHistoryObserver.php
> +        $history = $observer->getData()['status_history'];
```suggestion
        $history = $observer->getData()['status_history'] ?? null;
```

2023-07-17 12:41 UTC, EdieLemoine commented on Observer/SalesOrderStatusHistoryObserver.php
> +    private Data $helper;
check even of dit wel kan

2023-07-21 11:13 UTC, Mark-Ernst approved these changes

2023-07-21 11:47 UTC, merged