feat: add dhl carriers
myparcelnl/magento pull request #777
Opened 2023-09-28 13:50 UTC by joerivanveen

2023-10-04 15:12 UTC, Mark-Ernst submitted a review, later dismissed

2023-10-04 15:41 UTC, joerivanveen commented on Model/Rate/Result.php
> +            //$carrierPath = Data::CARRIERS_XML_PATH_MAP[$carrier];
Comment mag weg

2023-10-05 07:17 UTC, wthijmen submitted a review, later dismissed

2023-10-05 08:53 UTC, Mark-Ernst submitted a review, later dismissed

2023-10-05 08:57 UTC, wthijmen approved these changes

2023-10-17 07:30 UTC, EdieLemoine requested changes

2023-10-17 07:30 UTC, EdieLemoine commented on view/frontend/web/js/model/checkout.js
> +      if (document.getElementsByClassName('myparcel-delivery-options')) {
waarom check je of die div bestaat?

2023-10-17 11:28 UTC, Mark-Ernst commented on view/frontend/web/js/view/delivery-options.js
> +          street: address.street[0] || ''
Dat heeft ons aller Magento zo bepaald https://www.magentoextensions.org/documentation/class_magento_1_1_quote_1_1_model_1_1_quote_1_1_address.html#ad804bd3a7447b83b37d6de35f2056fb2

2023-10-18 08:11 UTC, EdieLemoine approved these changes

2023-10-18 08:28 UTC, Mark-Ernst submitted a review, later dismissed

2023-10-19 11:26 UTC, wthijmen approved these changes

2023-10-19 11:27 UTC, Mark-Ernst approved these changes

2023-10-19 11:27 UTC, merged