fix(checkout): consistently use correct package type for delivery options
myparcelnl/magento pull request #782
Opened 2023-11-03 15:00 UTC by joerivanveen

INT-237 wip

2023-11-09 08:17 UTC, wthijmen submitted a review, later dismissed

2023-11-09 10:55 UTC, EdieLemoine requested changes

2023-11-09 10:55 UTC, EdieLemoine commented on view/frontend/web/js/model/checkout.js
> +          if (el && (el = el.parentNode)) el.parentNode.removeChild(el);
waarom deze assignment in een if? leest ontzettend moeilijk. graag ook altijd een block `{...}` gebruiken

2023-11-09 11:25 UTC, wthijmen approved these changes

2023-11-10 09:41 UTC, EdieLemoine approved these changes

2023-11-10 09:53 UTC, merged