feat: add carrier ups
myparcelnl/magento pull request #787
Opened 2023-11-13 11:56 UTC by wthijmen

INT-181

2023-11-22 09:10 UTC, Mark-Ernst requested changes

2023-11-22 09:10 UTC, Mark-Ernst commented on etc/config.xml
> +            <pickup>
Heeft UPS wel pickup? Ik zie dat namelijk niet terug bij het aanmaken van een zending in de backoffice

2023-11-29 08:49 UTC, Mark-Ernst approved these changes

2023-11-30 14:29 UTC, joerivanveen submitted a review, later dismissed

2023-12-04 12:44 UTC, joerivanveen submitted a review, later dismissed

2023-12-04 12:50 UTC, Mark-Ernst approved these changes

2023-12-21 08:27 UTC, Mark-Ernst approved these changes

2023-12-21 08:35 UTC, merged