refactor: only set country if not null
myparcelnl/magento pull request #794
Opened 2023-11-24 15:33 UTC by wthijmen

Resolves #789

2023-11-27 08:51 UTC, EdieLemoine requested changes
dit is geen refactor

2023-11-27 08:51 UTC, EdieLemoine commented on Model/Sales/Package.php
> +        if ($currentCountry !== null) {
unhappy flow eerst

2023-11-29 14:13 UTC, Mark-Ernst approved these changes

2023-11-30 15:02 UTC, joerivanveen approved these changes

2023-12-01 16:04 UTC, EdieLemoine approved these changes

2023-12-01 16:04 UTC, EdieLemoine approved these changes

2023-12-01 16:05 UTC, merged