fix: use both address lines for street name
myparcelnl/magento pull request #819
Opened 2024-02-12 16:02 UTC by Mark-Ernst

INT-361

2024-02-13 08:23 UTC, wthijmen approved these changes

2024-02-14 14:10 UTC, EdieLemoine requested changes

2024-02-14 14:10 UTC, EdieLemoine commented on view/frontend/web/js/view/delivery-options.js
> +          street: address.street ? [address.street[0], address.street[1]].join(' ') : ''
```suggestion
          street: address.street ? [address.street[0], address.street[1]].join(' ').trim() : ''
```

2024-02-14 14:11 UTC, EdieLemoine submitted a review, later dismissed

2024-02-15 08:19 UTC, wthijmen approved these changes

2024-02-15 15:49 UTC, EdieLemoine approved these changes

2024-02-15 15:51 UTC, merged