feat: activate dpd for myparcel contract
myparcelnl/magento pull request #822
Opened 2024-03-04 13:39 UTC by Mark-Ernst

INT-374

2024-03-04 13:47 UTC, wthijmen approved these changes

2024-03-04 14:10 UTC, joerivanveen approved these changes

2024-03-05 15:39 UTC, RichardPerdaan submitted a review, later dismissed

2024-03-06 10:10 UTC, EdieLemoine requested changes
delvery options update mist in package.json/yarn.lock

2024-03-06 13:05 UTC, EdieLemoine approved these changes

2024-03-08 08:18 UTC, merged